version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update \
            && apk add --no-cache \
              ca-certificates \
              py-pip=9.0.0-r1 \
              wget \
              && update-ca-certificates
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Download Deepspeech models
          command: |
            cd app && wget -O - \
            https://github.com/mozilla/DeepSpeech/releases/download/v0.1.1/deepspeech-0.1.1-models.tar.gz | \
            tar xvfz -
            cd models && \
            wget -q https://s3-us-west-2.amazonaws.com/deepspeech/mmap/output_graph.pb -O output_graph.pb && \
            wget -q https://s3-us-west-2.amazonaws.com/deepspeech/mmap/output_graph.pbmm -O output_graph.pbmm
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
#      - run:
#          name: Run tests
#          command: docker run app

#            docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              TAG="0.1.${CIRCLE_BUILD_NUM}"
              docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
              docker tag app "csbain/deepspeech-knime-server:${TAG}"
              docker push "csbain/deepspeech-knime-server:${TAG}"
              docker tag app "csbain/deepspeech-knime-server:latest"
              docker push "csbain/deepspeech-knime-server:latest"
            fi

